version: "3.9"

services:
  mon_service:
    build:
      context: .
    container_name: compose_container
    image: mon_image
    command: /usr/local/bin/my_script.sh
    restart: unless-stopped
    tty: true

  nginx:
    image: nginx:latest
    container_name: mon_nginx
    ports:
      - "8080:80"  # Mappe le port 8080 de l'hôte au port 80 du conteneur
    restart: unless-stopped
